VARIABLE_NAME_ID = "ID"

VARIABLE_STATUS_EVENT = "event"
VARIABLE_STATUS_LENGTH = "length"

EXTENSION_VALID = [".json", ".xlsx", ".tsv"]
EXTENSION_SPREADSHEET = [".xlsx", ".tsv"]

SCRIPTS_FOLDER_NAME = "scripts"
REGISTERS_FOLDER_NAME = "registers"
VARIALBES_FOLDER_NAME = "variables"

DEFAULT_VALUE_GENERAL = None
DEFAULT_VALUE_LIST = []
DEFAULT_VALUE_OBJECT = {}

DEFAULT_VARIABLE_TYPE = "string"

RULES_DEFAULT_REQUIRED = False